package com.finallygo.collect.test.pojo;

/**
 * BookType generated by MyEclipse Persistence Tools
 */

public class BookType  {

	// Fields

	private Integer typeId;

	private String typeName;

	// Constructors

	/** default constructor */
	public BookType() {
	}

	/** full constructor */
	public BookType(String typeName) {
		this.typeName = typeName;
	}

	// Property accessors

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}